src/website/models.py
from . import db 
from flask_login import UserMixin

class User(db.Model, UserMixin):
    id = db.Column(db.Integer, primary_key=True)
    email = db.Column(db.String(150), unique=True)
    password = db.Column(db.String(150))
    first_name = db.Column(db.String(150))
    files = db.relationship("File")

class File(db.Model):
    id = db.Column(db.Integer, primary_key=True)
    original_filename = db.Column(db.String(100))
    filename = db.Column(db.String(100))
    bucket = db.Column(db.String(100))
    region = db.Column(db.String(100))
    user_id = db.Column(db.Integer, db.ForeignKey('user.id'))

src/website/__init__.py
from flask import Flask
from flask_sqlalchemy import SQLAlchemy
from os import path
import os
from flask_login import LoginManager
from dotenv import load_dotenv
import boto3

load_dotenv()
secret_key = os.getenv('SECRET_KEY')

db = SQLAlchemy()
DB_NAME = "database.db"


def create_app():
    app = Flask(__name__)
    app.config['SECRET_KEY'] = secret_key
    app.config['SQLALCHEMY_DATABASE_URI'] = f'sqlite:///{DB_NAME}'
    db.init_app(app)

    from .views import views
    from .auth import auth

    app.register_blueprint(views, url_prefix='/')
    app.register_blueprint(auth, url_prefix='/')

    app.config['MAX_CONTENT_LENGTH'] = 100 * 1024 * 1024

    from .models import User, File

    create_database(app)

    login_manager = LoginManager()
    login_manager.login_view = 'auth.login'
    login_manager.init_app(app)

    @login_manager.user_loader
    def load_user(id):
        return User.query.get(int(id))

    return app

def create_database(app):
    with app.app_context():
        db.create_all()

AWS_ACCESS_KEY_ID = os.getenv('AWS_ACCESS_KEY')
AWS_SECRET_ACCESS_KEY = os.getenv('AWS_SECRET_KEY')

def get_bucket():
    s3 = boto3.resource('s3', 
        aws_access_key_id=AWS_ACCESS_KEY_ID,
        aws_secret_access_key=AWS_SECRET_ACCESS_KEY)
    
    return s3

src/website/auth.py
from flask import Blueprint, render_template, request, flash, redirect, url_for, session
from flask_login import login_user, login_required, logout_user, current_user
from .models import User
from werkzeug.security import generate_password_hash, check_password_hash
from . import db

auth = Blueprint('auth', __name__)

@auth.route('/login', methods=['GET', 'POST'])
def login():
    if request.method == 'POST':
        email = request.form.get('email')
        password = request.form.get('password')

        user = User.query.filter_by(email=email).first()
        if user:
            if check_password_hash(user.password, password):
                flash('Login successful!', category='success')
                login_user(user, remember=True)
                if session.__contains__('llm_response'):
                    session.pop('llm_response')
                return redirect(url_for('views.home'))
            else:
                flash('Incorrect password!', category='error')
        else:
            flash('No existing account with this email.', category='error')

    return render_template("login.html", user=current_user)
    
@auth.route('/logout')
@login_required
def logout():
    logout_user()
    return redirect(url_for('auth.login'))

@auth.route('/sign-up', methods=['GET', 'POST'])
def sign_up():
    if request.method == 'POST':
        email = request.form.get('email')
        first_name = request.form.get('firstName')
        password1 = request.form.get('password1')
        password2 = request.form.get('password2')

        user = User.query.filter_by(email=email).first()
        if user:
            flash('Email already exists!', category='error')
        elif len(email) < 4:
            flash('Email not valid', category='error')
        elif len(first_name) < 2:
            flash('First name must be greater than 1 character', category='error')
        elif password1 != password2:
            flash('passwords do not math', category='error')
        elif len(password1) < 7:
            flash('password length must be greater than 6 characters', category='error')
        else:
            # User info is valid, so add to database
            new_user = User(email=email, first_name=first_name, password=generate_password_hash(password1, method='pbkdf2:sha256'))
            db.session.add(new_user)
            db.session.commit()
            login_user(new_user, remember=True)
            flash('Account Successfully Created!', category='success')
            return redirect(url_for("views.home"))

    return render_template("sign-up.html", user=current_user)

src/website/views.py
from flask import Blueprint, render_template, request, redirect, url_for, flash, session, jsonify
from flask_login import login_required, current_user
from .models import User, File
import boto3
import uuid
import os
from . import db
from . import get_bucket
from dotenv import load_dotenv
from qdrant.vectorDatabase import VectorDatabase
from qdrant.llm import Query
import json


load_dotenv()


ALLOWED_EXTENSIONS = {'application/pdf', 'md'}

def allowed_file(file):
    return file.content_type in ALLOWED_EXTENSIONS


views = Blueprint('views', __name__)

@views.route('/', methods=['GET', 'POST'])
def index():
    return render_template("index.html")

@views.route('/home', methods=['GET', 'POST'])
@login_required
def home():
    if request.method == 'POST':
        uploaded_file = request.files['file-to-save']
        if not allowed_file(uploaded_file):
            flash('File type not allowed', category='error')
            return(redirect(url_for('views.home')))
        
        new_filename = uuid.uuid4().hex + '.' + uploaded_file.filename.lower()
        
        bucket_name = 'makerag'
        s3 = get_bucket()
        s3.Bucket(bucket_name).upload_fileobj(uploaded_file, new_filename)

        file = File(original_filename=uploaded_file.filename, filename=new_filename,
            bucket=bucket_name, user_id=current_user.id, region="us-east-2")
        
        db.session.add(file)
        db.session.commit()

        return(redirect(url_for('views.home')))
    
    
    files = File.query.filter_by(user_id=current_user.id).all()
    return render_template("home.html", user=current_user, files=files, llm_response=session.get('llm_response'))

    


@views.route('/createdb', methods=['GET','POST'])
@login_required
def create_vector_database():
    files = File.query.filter_by(user_id=current_user.id).all()
    file_ids = [file.filename for file in files]
    vdb = VectorDatabase()
    vdb.createDatabase(current_user.id, file_ids)

    return(redirect(url_for('views.home')))

@views.route('/querydb', methods=['GET','POST'])
@login_required
def query_vector_db():

    query_text = request.form.get('query_text')

    vdb = VectorDatabase()
    querier = Query()

    context = vdb.searchDatabase(current_user.id, query_text)
    llm_response = querier.query(query_text, context)
    session['llm_response'] = llm_response
    
    return(redirect(url_for('views.home')))

@views.route('/delete-file', methods=['POST'])
def delete_file():  
    file_json = json.loads(request.data)
    file_id = file_json.get('id')
    file = File.query.get(file_id)
    if file:
        if file.user_id == current_user.id:
            db.session.delete(file)
            db.session.commit()
            bucket_name = 'makerag'
            s3 = get_bucket()
            s3.Object(bucket_name, file.filename).delete()

    return jsonify({})

@views.errorhandler(413)
def request_entity_too_large(error):
    flash('File too large', category='error')
    return(redirect(url_for('views.home')))
   

src/website/templates/base.html
<!DOCTYPE html>
<html>
  <head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1" />
    <link
      rel="stylesheet"
      href="https://stackpath.bootstrapcdn.com/bootstrap/4.4.1/css/bootstrap.min.css"
      integrity="sha384-Vkoo8x4CGsO3+Hhxv8T/Q5PaXtkKtu6ug5TOeNV6gBiFeWPGFN9MuhOf23Q9Ifjh"
      crossorigin="anonymous"
    />
    <link
      rel="stylesheet"
      href="https://stackpath.bootstrapcdn.com/font-awesome/4.7.0/css/font-awesome.min.css"
      crossorigin="anonymous"
    />

    <title>{% block title %}Home{% endblock %}</title>
    <style>
      body {
    width: 100vw;
    height: 100vh;
    overflow: hidden;
    background-color: #F4FFFD;
    background-image: radial-gradient(rgb(215, 215, 215) 1px, transparent 0);
    background-size: 40px 40px;
    background-position: -19px -19px;
    margin: 0;
    padding: 0
}
    </style>
  </head>
  
  <body>
    {% if user.is_authenticated %}
    <nav class="navbar navbar-expand-lg navbar-dark bg-dark">
      <button
        class="navbar-toggler"
        type="button"
        data-toggle="collapse"
        data-target="#navbar"
      >
        <span class="navbar-toggler-icon"></span>
      </button>
      <div class="collapse navbar-collapse" id="navbar">
        <div class="navbar-nav">
        
          <a class="nav-item nav-link" id="home" href="/">Home</a>
          <a class="nav-item nav-link" id="logout" href="/logout">Logout</a>
        
        </div>
      </div>
    </nav>
    {% endif %}

    {% with messages = get_flashed_messages(with_categories=true) %}
        {% if messages %}
        <div style="position: absolute; bottom: 0; right: 5px">
            {% for category, message in messages %}
                {% if category == 'error' %}
                    <div class="alert alert-danger alter-dismissable fade show" role="alert">
                        {{ message }}
                        <button type="button" class="close" data-dismiss="alert">
                            <span aria-hidden="true">&times;</span>
                        </button>
                    </div>
                {% else %}
                    <div class="alert alert-success alter-dismissable fade show" role="alert">
                        {{ message }}
                        <button type="button" class="close" data-dismiss="alert">
                            <span aria-hidden="true">&times;</span>
                        </button>
                    </div>
                {% endif %}
            {% endfor %}
          </div>
        {% endif %}
    {% endwith %}

    <div class="container mx-auto">{% block content %} {% endblock %}</div>


    <script
      src="https://code.jquery.com/jquery-3.2.1.slim.min.js"
      integrity="sha384-KJ3o2DKtIkvYIK3UENzmM7KCkRr/rE9/Qpg6aAZGJwFDMVNA/GpGFF93hXpG5KkN"
      crossorigin="anonymous"
    ></script>
    <script
      src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.12.9/umd/popper.min.js"
      integrity="sha384-ApNbgh9B+Y1QKtv3Rn7W3mgPxhU9K/ScQsAP7hUibX39j7fakFPskvXusvfa0b4Q"
      crossorigin="anonymous"
    ></script>
    <script
      src="https://maxcdn.bootstrapcdn.com/bootstrap/4.0.0/js/bootstrap.min.js"
      integrity="sha384-JZR6Spejh4U02d8jOt6vLEHfe/JQGiRRSQQxSfFWpi1MquVdAyjUar5+76PVCmYl"
      crossorigin="anonymous"
    ></script>
  </body>

  <script>
    type='text/javascript'
    src='{{ url_for("static", filename="home.js") }}'
  </script>

  {% block javascript %}
    <script type="text/javascript">
      function deleteFile(id) {
    fetch("/delete-file", {
    method: "POST",
    body: JSON.stringify({ id: id }),
    }).then((_res) => {
    window.location.href = "/home";
    });
    }
    </script>
  {% endblock %}
</html>

src/website/templates/home.html
{% extends "base.html" %} {% block title %}Home{% endblock %} {% block content%}
<div class="d-flex vh-100 mt-3">
  <div class="col">
    <div class="bg-white shadow-sm p-3 w-100 m-0 mb-2" style="margin: 10px; border-radius: 10px; height: 80vh;">
      <h3 style="font-size: 20px; margin: 0">Chatbot Files</h3>
      <hr class="m-0 mb-2 mt-2"></hr>
        {% if files %}
          {% for file in files %}
            <li class="list-group-item">{{ file.original_filename }}
              <button type="button" class="close" onClick="deleteFile({{ file.id }})">
                <span aria-hidden="true">&times;</span>
              </button>
            </li>
          {% endfor %}
        {% else %}
        <p style="font-family:monospace">Get started by uploading files to provide context to the chatbot!</p>

        {% endif %}
    </div>

    <div class="bg-white shadow-sm pl-2 pr-2 pt-1" style="border-radius: 10px; height: 50px;">
        <form
        method="POST"
        enctype="multipart/form-data"
        style="margin-bottom: 30px; display: flex; justify-content: space-between;"
      >
        <input type="file" , name="file-to-save" class="mt-1"/>
        <button type="submit" class="btn btn-primary">Add File</button>
      </form>

    </div>
  </div>

  <div class="col">
    
    <div class="bg-white shadow-sm p-3 w-100 m-0 mb-2" style="margin: 10px; border-radius: 10px; height: 80vh;">
      <form action="/createdb" method="post">
        <button class="btn btn-primary" type="submit">Create Database</button>
      </form>
        <h3 style="font-size: 20px; margin: 0">Test Chatbot</h3>
        <hr class="m-0 mb-2 mt-2"></hr>
        {% if llm_response %}{{llm_response}}{% endif %}

    </div>
      <form action="/querydb" method="post">
        <div class="bg-white shadow-sm p-2" style="border-radius: 10px; height: 50px;">
          <input type="text" id="query_text" name="query_text" style="width: 86%; height: 100%; border-radius: 10px; border: 1px solid gray">
          <button class="btn btn-primary" type="submit">Send</button>
        </div>
      </form>
    </div>
</div>

{% endblock %}

src/website/templates/index.html
<!DOCTYPE html>
<html>
    <head>
        <meta name="viewport" content="width=device-width, initial-scale=1.0">
        <title>MakeRAG</title>
        <link rel="stylesheet" href="{{ url_for('static',filename='index_style.css') }}">
    </head>

    <body style="background-color: lightcoral;">
        <nav class="navbar fixed-top navbar-expand-lg navbar-light navbar-custum">
            <div class="collapse navbar-collapse" id="navbarText">
              <ul class="navbar-nav mr-auto">
                <li class="nav-item">
                  <a class="nav-link" href="{{ url_for('auth.login') }}" style="color: #fff; font-size: 20px; font-family: monospace;">login</a>
                </li>
                <li class="nav-item">
                  <a class="nav-link" href="{{ url_for('auth.sign_up') }}" style="color: #fff; font-size: 20px; font-family: monospace;">sign-up</a>
                </li>
              </ul>
            </div>
          </nav>
        <div class="hero">
            <div class="title">
                <h1>The Future of Large Language Models is Here</h1>
                <div class="back-text">
                    <span>M</span>
                    <span>A</span>
                    <span>K</span>
                    <span>E</span>
                    <span>R</span>
                    <span>A</span>
                    <span>G</span>
                </div>
            </div>
        </div>
        <div class="information">
            <h1>How it works</h1>
        </div>
    <script>

    let spanTexts = document.getElementsByTagName("span");

        window.onload = function(){
            for(spanText of spanTexts){
                spanText.classList.add("active");
            }
        }

    </script>
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.3.3/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-QWTKZyjpPEjISv5WaRU9OFeRpok6YctnYmDr5pNlyT2bRjXh0JMhjY6hW+ALEwIH" crossorigin="anonymous">
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.3.3/dist/js/bootstrap.bundle.min.js" integrity="sha384-YvpcrYf0tY3lHB60NNkmXc5s9fDVZLESaAA55NDzOxhy9GkcIdslK1eN7N6jIeHz" crossorigin="anonymous"></script>
    </body>
</html>

src/website/templates/login.html
{% extends "base.html" %} {% block title %}Login{% endblock %} {% block content %}
<div class="d-flex vh-100 align-items-center">
  <div class="col">
    <form method="POST" class="w-75 p-4 bg-white shadow mb-5" style="border-radius: 20px;">
      <h3 class="mb-4"><b>Login</b></h3>
      <div class="form-group">
        <label for="email" class="mb-1">Email Address</label>
        <input
          type="email"
          class="form-control"
          id="email"
          name="email"
          placeholder="Enter email"
        />
      </div>
      <div class="form-group">
        <label for="password" class="mb-1">Password</label>
        <input
          type="password"
          class="form-control"
          id="password"
          name="password"
          placeholder="Enter password"
        />
      </div>
      <div style="display: flex; align-items: center; justify-content: space-between;" class="mb-3">
        <div>
          <input type="checkbox"><span> Remember me</span>
    </div>
    <div>
      
      <a class="mb-1" href="/forgotpass">Forgot password?</a>
    </div>
    </div>
    <button type="submit" class="btn btn-primary w-100 mb-3">Login</button>

      <p align="center">Don't have an account? <a href="/sign-up" style="color: #539987;">Sign up</a></p>
    </form>
  </div>
  <div class="col">
    <div style="display: flex; flex-direction: column; justify-content: space-between;" class="mb-5">
    <p style="font-size: 100px; font-weight: bold; font-family:monospace; line-height :60%;">
    makerag
  </p>
  <p style="font-size: 50px; font-weight: bold; font-family:monospace; line-height: 70%;">.com</p>
  <br><br>
  <p style="font-family: monospace;">Create an AI Chatbot with personalized information in seconds.</p>
  </div>
</div>
</div>

    {% endblock %}

src/website/templates/sign-up.html
{% extends "base.html" %} {% block title %}Sign Up{% endblock %} {% block
    content %}
    <div class="d-flex vh-100 align-items-center">
      <div class="col">
        <form method="POST" class="w-75 p-4 bg-white shadow mb-5" style="border-radius: 20px;">
          <h3 class="mb-4"><b>Sign up</b></h3>
          <div class="form-group">
            <label for="email">Email Address</label>
            <input
              type="email"
              class="form-control"
              id="email"
              name="email"
              placeholder="Enter email"
            />
          </div>
          <div class="form-group">
            <label for="firstName">First Name</label>
            <input
              type="text"
              class="form-control"
              id="firstName"
              name="firstName"
              placeholder="Enter first name"
            />
          </div>
          <div class="form-group">
            <label for="password1">Password</label>
            <input
              type="password"
              class="form-control"
              id="password1"
              name="password1"
              placeholder="Enter password"
            />
          </div>
          <div class="form-group">
            <label for="password2">Re-enter password</label>
            <input
              type="password"
              class="form-control"
              id="password2"
              name="password2"
              placeholder="Confirm password"
            />
          </div>
          <br />
          <p style="color: gray; font-size: 13px;">By signing up you agree with our terms of service.</p>
          
        <button type="submit" class="btn btn-primary w-100 mb-3">Sign up</button>
    
          <p align="center">Already have an account? <a href="/login">Log in</a></p>
        </form>
      </div>
      <div class="col">
        <div style="display: flex; flex-direction: column; justify-content: space-between;" class="mb-5">
        <p style="font-size: 100px; font-weight: bold; font-family:monospace; line-height :60%;">
        makerag
      </p>
      <p style="font-size: 50px; font-weight: bold; font-family:monospace; line-height: 70%;">.com</p>
      <br><br>
      <p style="font-family: monospace;">Create an AI Chatbot with personalized information in seconds.</p>
      </div>
    </div>
    </div>


      
    {% endblock %}